TimeStamp: "2018-10-10 10:09:23"
Address: "shenzhen"
Postcode: 518000
CompanyInfomation:
  Name: "lixin"
  MarketCapitalization: 3483
  EmployeeNum: 200
  Department:
    - "fder"
    - "dfadf"
    - "djfkdjf"
    - "sll"
  Isopen: false